security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: Email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: Email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
           # anonymous: true 
            jwt: ~

    access_control:
        #- { path: ^/api/login, roles: PUBLIC_ACCESSS}
        #- { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/api/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY } 
        # Routes pour lesquelles aucun authentification n'est nécessaire
        #- { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/caissier, roles: ROLE_CAISSIER }
       # - { path: ^/api/tickets, roles: ROLE_USER }
      #  - { path: ^/api, roles: ROLE_USER }
        # - { path: ^/api, roles: ROLE_USER }
        - { path: ^/api/user/lot, roles: ROLE_USER }
        #Routes pour les CAISSIER  
       # - { path: ^/api/ticket/validation, roles: ROLE_CAISSIER}
       


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 25
                memory_cost: 10



